# Generated by Django 5.0.2 on 2024-02-09 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('primary_breed', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=100)),
                ('primary_color', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=250)),
                ('photos', models.JSONField()),
                ('contact', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('location', models.CharField(max_length=50)),
                ('phone', models.IntegerField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animalId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.animal')),
                ('profileId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.profile')),
            ],
        ),
    ]
