# Generated by Django 5.0.2 on 2024-02-09 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_favorite_profileid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='primary_breed',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='primary_color',
        ),
        migrations.AddField(
            model_name='animal',
            name='breed',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animal',
            name='color',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
    ]
