# Generated by Django 5.0.2 on 2024-02-10 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_animal_primary_breed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='breed',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='animal',
            name='color',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='animal',
            name='contact',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='animal',
            name='description',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='photos',
            field=models.JSONField(default=list),
        ),
    ]
